execute pathogen#infect()

" Learned and copied form http://dougblack.io/words/a-good-vimrc.html



colorscheme badwolf

syntax enable

set backspace=2 " more powerful backspacing

set tabstop=4 " number of visual spaces per tab
set softtabstop=4 " number of space sin tab when editing
set expandtab " tabs are space
set shiftwidth=4 " size of an indent

set number   " show line numbers
set showcmd  " show command in bottom bar
set cursorline " highlight current line

filetype indent on " load filetype specific indent files

set wildmenu " visual autocompletet for command menu

set lazyredraw " Only redraw screen when needed

set showmatch " highlight matching braces
set incsearch " search as characters are entered
set hlsearch " highlight matches

" turn off highlight
nnoremap <leader><space> :nohlsearch<CR>

set foldenable  " enable code folding
set foldlevelstart=10 " open most folds by default
set foldnestmax=10 " Nesting folds

" space open/closes folds
nnoremap <space> za
set foldmethod=indent  " fold based on indent level

" move vertically by visual line
nnoremap j gj
nnoremap k gk

" move to beginning/end of line
nnoremap B ^
nnoremap E $

" highlight last inserted text
nnoremap gV `[v`]


let mapleader=","  " leader is comma

" jk is escape
inoremap jk <esc>

" toggle graphical undo
nnoremap <leader>u :GundoToggle<CR>

" save session
nnoremap <leader>s :mksession<CR>

let g:ctrlp_match_window = 'bottom,order:ttb'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0
let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'

" for pasting without blowup
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode
